FROM debian:8
MAINTAINER Smile <erp@smile.fr>

# Install packages required to:
# * install Python packages via PyPi: python-pip
# * install Node.js packages: npm
# * check code quality: cloc python-coverage python-flake8
# * install unit tests package: python-unittest2
# * download and install wkhtmltopdf
# * configure locale
RUN apt-get update \
    && apt-get install -y --no-install-recommends python-pip npm cloc python-coverage python-flake8 python-unittest2 \
    wget fontconfig libfontconfig1 libfreetype6 libpng12-0 libjpeg62-turbo libx11-6 libxext6 libxrender1 xfonts-base xfonts-75dpi \
    && apt-get install -fy \
    && ln -s /usr/bin/nodejs /usr/bin/node \
    && cd /tmp && wget http://nightly.odoo.com/extra/wkhtmltox-0.12.1.2_linux-jessie-amd64.deb \
    && dpkg --force-depends -i wkhtmltox*.deb \
    && apt-get -y install locales \
    && sed -i '/en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen \
    && locale-gen en_US.UTF-8

# Set locale
ENV LANG en_US.UTF-8

# Install Odoo requirements, recommandations and specific packages
RUN apt-get install -y %(system_packages)s

# Install PyPI requirements
RUN pip install -q %(pip_packages)s

# Install Node.js requirements
RUN npm install -g %(npm_packages)s

# Create Odoo user and sources directory
RUN adduser odoo --disabled-password
RUN mkdir -p %(odoo_dir)s

# Install specific system requirements
RUN apt-get install -y %(specific_system_packages)s

# Install specific PyPI requirements
RUN pip install -q %(specific_pip_packages)s

# Install specific Node.js requirements
RUN npm install -g %(specific_npm_packages)s
