FROM %(base_image)s
MAINTAINER Smile <erp@smile.fr>

# Download Odoo sources
ADD . %(odoo_dir)s
RUN chown -R odoo:odoo %(odoo_dir)s

# Set the working directory
WORKDIR %(odoo_dir)s

# Check existance of server command and server conf
RUN [ -f "/usr/bin/python" ]
RUN [ -f "%(server_cmd)s" ]
RUN [ -f "server.conf" ]

# Expose port
EXPOSE 8069 8072

# Set the default command to run when starting the container
USER odoo
ENTRYPOINT ["/usr/bin/python", "%(server_cmd)s", "-c", "server.conf"]
CMD ["--load=web,smile_test,smile_upgrade"]
