FROM debian:9
MAINTAINER Smile <erp@smile.fr>

# Install packages required to:
# * install Python packages via PyPi: python-pip
# * install Node.js packages: npm
# * check code quality: cloc python-coverage python-flake8
# * install unit tests package: python-unittest2
# * download and install wkhtmltopdf
# * configure locale
RUN apt-get update \
    && apt-get install -y --no-install-recommends python-pip cloc python-coverage python-flake8 python-unittest2 \
    wget curl sudo software-properties-common gnupg fontconfig libfontconfig1 libfreetype6 libjpeg62-turbo \
    libx11-6 libxext6 libxrender1 xfonts-base xfonts-75dpi libssl1.0-dev xz-utils \
    && apt-get install -fy \
    && curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - \
    && apt-get install -y nodejs \
    && curl -o wkhtmltox.tar.xz -SL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz \
    && echo '3f923f425d345940089e44c1466f6408b9619562 wkhtmltox.tar.xz' | sha1sum -c - \
    && tar xvf wkhtmltox.tar.xz \
    && cp wkhtmltox/lib/* /usr/local/lib/ \
    && cp wkhtmltox/bin/* /usr/local/bin/ \
    && cp -r wkhtmltox/share/man/man1 /usr/local/share/man/ \
    && apt-get -y install locales \
    && sed -i '/en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen \
    && locale-gen en_US.UTF-8

# Set locale
ENV LANG en_US.UTF-8

# Install Odoo requirements, recommandations and specific packages
RUN apt-get install -y %(system_packages)s

# Install PyPI requirements
RUN pip install -q %(pip_packages)s

# Install Node.js requirements
RUN npm install -g %(npm_packages)s

# Create Odoo user and sources directory
RUN adduser odoo --disabled-password
RUN mkdir -p %(odoo_dir)s

# Install specific system requirements
RUN apt-get install -y %(specific_system_packages)s

# Install specific PyPI requirements
RUN pip install -q %(specific_pip_packages)s

# Install specific Node.js requirements
RUN npm install -g %(specific_npm_packages)s
