FROM fedora:23
MAINTAINER Smile <erp@smile.fr>

# Install packages required to:
# * install Python packages via PyPi: python-pip
# * install Node.js packages: npm
# * check code quality: cloc python-coverage python-flake8
# * install unit tests package: python-unittest2
# * download and install wkhtmltopdf
RUN dnf install -y python2 python-pip npm cloc python-coverage python-flake8 python-unittest2 \
    wget fontconfig libfontconfig.so.1 libXext libXrender libpng15 libjpeg-turbo openssl urw-fonts \
    && cd /tmp && wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.1/wkhtmltox-0.12.1_linux-centos7-amd64.rpm \
    && rpm -Uvh wkhtmltox*.rpm

# Install Odoo requirements, recommandations and specific packages
RUN dnf install -y %(system_packages)s

# Install PyPI requirements
RUN pip install -q %(pip_packages)s

# Install Node.js requirements
RUN npm install -g %(npm_packages)s

# Create Odoo user and sources directory
RUN useradd odoo
RUN mkdir -p %(odoo_dir)s

# Install specific system requirements
RUN dnf install -y %(specific_system_packages)s

# Install specific PyPI requirements
RUN pip install -q %(specific_pip_packages)s

# Install specific Node.js requirements
RUN npm install -g %(specific_npm_packages)s
