FROM ubuntu:14.04
MAINTAINER Smile <erp@smile.fr>

# Add PostgreSQL's source
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8 \
	&& echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
	&& apt-get update

# Configure locales
RUN locale-gen en_US.UTF-8 && update-locale && echo 'LANG="en_US.UTF-8"' > /etc/default/locale

# Install packages required to:
# * install Python package vi PyPi: python-pip
# * check quality code: cloc python-coverage python-flake8
# * install unit tests package: python-unittest2
# * download and install wkhtmltopdf: wget fontconfig libfontconfig1 libfreetype6 libjpeg-turbo8 libx11-6 libxext6 libxrender1
RUN apt-get -qq update && apt-get -qq -y install python-pip \
	cloc python-coverage python-flake8 \
	python-unittest2 \
	wget fontconfig libfontconfig1 libfreetype6 libpng12-0 zlib1g libjpeg-turbo8 libssl1.0.0 libx11-6 libxext6 libxrender1 xfonts-base xfonts-75dpi libstdc++6 libc6 \
        && cd /tmp && wget http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb \
        && dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
# Install PostgreSQL
RUN apt-get -qq -y install postgresql

# Setup PostgreSQL
USER postgres
RUN /etc/init.d/postgresql start && psql --command "CREATE USER odoo WITH SUPERUSER PASSWORD 'odoo';"
USER root

# Install Odoo requirements, recommandations and specific packages
RUN apt-get -qq -y install %(required_packages)s %(optional_packages)s %(specific_packages)s

# Install PIP requirements
RUN pip -q install %(pip_packages)s

# Download Odoo sources
RUN mkdir -p /usr/src/odoo
RUN adduser odoo --disabled-password
COPY . /usr/src/odoo
RUN chown -R odoo:odoo /usr/src/odoo

# Expose port
EXPOSE 8069

# Set the default command to run when starting the container
CMD ["/usr/src/odoo/launcher.sh"]
