FROM ubuntu:14.04
MAINTAINER Smile <erp@smile.fr>

# Add PostgreSQL PGP key. Cf. https://www.postgresql.org/media/keys/ACCC4CF8.asc 
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

# Add PostgreSQL's source
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" > /etc/apt/sources.list.d/pgdg.list

# Update packages list
RUN apt-get -qq update

# Configure locales
RUN locale-gen en_US.UTF-8 && update-locale
RUN echo 'LANG="en_US.UTF-8"' > /etc/default/locale

# Install PostgreSQL
RUN apt-get -qq -y install postgresql-%(pg_version)s

# Setup PostgreSQL
USER postgres
RUN /etc/init.d/postgresql start && psql --command "CREATE USER odoo WITH SUPERUSER PASSWORD 'odoo';"
USER root

# Install packages required to check quality code and pip installation
RUN apt-get -qq -y install cloc python-coverage python-flake8 python-pip

# Install wkhtmltopdf
RUN apt-get -qq -y install wget fontconfig libfontconfig1 libfreetype6 libjpeg-turbo8 libx11-6 libxext6 libxrender1
RUN cd /tmp
RUN wget http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
RUN dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb

# Install Odoo requirements
RUN apt-get -qq -y install %(required_packages)s

# Install Odoo recommandations
RUN apt-get -qq -y install %(optional_packages)s

# Install specific packages
RUN apt-get -qq -y install %(specific_packages)s

# Install PIP requirements
RUN pip -q install %(pip_packages)s

# Download Odoo sources
RUN mkdir -p /usr/src/odoo
RUN adduser odoo --disabled-password
ADD . /usr/src/odoo
RUN chown -R odoo:odoo /usr/src/odoo

# Expose port
EXPOSE 8069

# Set the default command to run when starting the container
CMD ["/usr/src/odoo/launcher.sh"]
